### ISSUE TITLE
(':' TypeBoundList?)?

### ISSUE THREAD

**Issue by Apanatshka** [rust-analyzer/ungrammar#5]
I see a pattern of `(':' TypeBoundList?)?` in the rust ungrammar, and I'm wondering: Is there really going to be a case where there's just a colon without anything after it? Shouldn't it be `(':' TypeBoundList)?` instead?

**Comment by dtolnay** [comment]
Just the colon is legal syntax.

```rust
trait Trait<'a:, T:> where T: {
    type A:;
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=656b9b9276013473e9c30e03cba5d356

**Comment by dtolnay** [comment]
I think it's a bug in the ungrammar that it doesn't handle `where T:`.

https://github.com/rust-analyzer/ungrammar/blob/07d5806c9345e43c5fb2baa427bc149c8808a10f/rust.ungram#L272-L276

https://github.com/rust-analyzer/ungrammar/blob/07d5806c9345e43c5fb2baa427bc149c8808a10f/rust.ungram#L541-L546
^ It requires at least one `'lifetime'` or `Type` after the colon in a where-clause, which is not required by Rust.

**Comment by Apanatshka** [comment]
Huh, TIL. Do you know why the Rust grammar is so permissive? Was that an explicit design choice? I imagine it might be to avoid annoying parse error messages that are just pedantic. Still, I'm used to stricter syntax from other languages.

**Comment by matklad** [comment]
Yeah, it’s a bug that we don‘t allow T:. There’s also more general problem here which might or might not be worth fixing around here.

Rust restricts bounds to Paths, ungrammar allows Types as bounds. The reason for this is historical: when parsing impl Trait for Type, it’s easier to parse both as types.

This actually is problematic in rust-analyzer itself, because we carry this more permissive Type way to far into the lowering. So maybe we should adjust grammar around here to only allow paths for places which need to refer to traits.

**Comment by dtolnay** [comment]
> Do you know why the Rust grammar is so permissive? Was that an explicit design choice?

Yes it's for benefit of macros.

```rust
macro_rules! m {
    (...) => {
        trait Trait<T> where T: $($bound +)*
    };
}
```

where `$bound` may comprise 0 or more bounds.

**Comment by Veykril** [comment]
Closing as the grammar file is no longer maintained
